// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "WPILib.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<frc::SpeedController> driveSystemDriveMotorFrontLeft;
	static std::shared_ptr<frc::SpeedController> driveSystemDriveMotorRearLeft;
	static std::shared_ptr<frc::SpeedController> driveSystemDriveMotorFrontRight;
	static std::shared_ptr<frc::SpeedController> driveSystemDriveMotorRearRight;
	static std::shared_ptr<frc::RobotDrive> driveSystemMainDrive;
	static std::shared_ptr<frc::SpeedController> turningSystemTurnMotorFrontLeft;
	static std::shared_ptr<frc::Encoder> turningSystemQuadratureFrontLeft;
	static std::shared_ptr<frc::PIDController> turningSystemTurnFrontLeft;
	static std::shared_ptr<frc::SpeedController> turningSystemTurnMotorRearLeft;
	static std::shared_ptr<frc::Encoder> turningSystemQuadratureRearLeft;
	static std::shared_ptr<frc::PIDController> turningSystemTurnRearLeft;
	static std::shared_ptr<frc::SpeedController> turningSystemTurnMotorFrontRight;
	static std::shared_ptr<frc::Encoder> turningSystemQuadratureFrontRight;
	static std::shared_ptr<frc::PIDController> turningSystemTurnFrontRight;
	static std::shared_ptr<frc::SpeedController> turningSystemTurnMotorRearRight;
	static std::shared_ptr<frc::Encoder> turningSystemQuadratureRearRight;
	static std::shared_ptr<frc::PIDController> turningSystemTurnRearRight;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	static void init();
};
#endif
