// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef TURNINGSYSTEM_H
#define TURNINGSYSTEM_H

#include "Commands/PIDSubsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class TurningSystem: public frc::PIDSubsystem {
 public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<frc::SpeedController> turnMotorFrontLeft;
	std::shared_ptr<frc::Encoder> quadratureFrontLeft;
	std::shared_ptr<frc::PIDController> turnFrontLeft;
	std::shared_ptr<frc::SpeedController> turnMotorRearLeft;
	std::shared_ptr<frc::Encoder> quadratureRearLeft;
	std::shared_ptr<frc::PIDController> turnRearLeft;
	std::shared_ptr<frc::SpeedController> turnMotorFrontRight;
	std::shared_ptr<frc::Encoder> quadratureFrontRight;
	std::shared_ptr<frc::PIDController> turnFrontRight;
	std::shared_ptr<frc::SpeedController> turnMotorRearRight;
	std::shared_ptr<frc::Encoder> quadratureRearRight;
	std::shared_ptr<frc::PIDController> turnRearRight;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	TurningSystem();
	double ReturnPIDInput() override;
	void UsePIDOutput(double output) override;
	void InitDefaultCommand() override;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
};

#endif
